
#  dla uruchomienia na dockerze n1
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql:3306/prima_sosnowiec
#    username: root
#    password: 11mysql11
#  liquibase:
#    contexts: prod

#  dla uruchomienia na dockerze  n2
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/prima_sosnowiec
#    username: root
#    password: 11mysql11
#  liquibase:
#    contexts: prod


#  dla uruchomienia na dysku moim
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/prima_sosnowiec
    username: root
    password: 11mysql11
  liquibase:
    contexts: prod


#  dla uruchomienia na serwerze nadia
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://194.182.80.100:3306/prima_sosnowiec
#    username: root
#    password: 11mysql11
#  liquibase:
#    contexts: prod


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://mysql:3306/prima_sosnowiec
#    username: root
#    password: 11mysql11
#  liquibase:
#    contexts: prod