spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    hibernate:
      ddl-auto: none

#spring:
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#  liquibase:
#    change-log: classpath:db/master.xml
#  sql:
#    init:
#      mode: never
#  profiles:
#    default: dev
#
#  security:
#    user:
#      name: admin
#      password: hardPassword


# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#  spring.datasource.url = jdbc:mysql://localhost:3306/prima_sosnowiec
#  spring.datasource.username = root
#  spring.datasource.password = 11mysql11
#  spring.jpa.show-sql = true
